export const FETCH_ADMIN_CONTACT = 'bds/help/FETCH_ADMIN_CONTACT';
export const FETCH_ADMIN_CONTACT_SUCCESS = 'bds/help/FETCH_ADMIN_CONTACT_SUCCESS';
export const FETCH_ADMIN_CONTACT_ERROR = 'bds/help/FETCH_ADMIN_CONTACT_ERROR';